services:
    anvil:
        image: ghcr.io/foundry-rs/foundry:nightly-503792a1dbadd901a4c02f6fcd1de1caff1573ff
        platform: linux/amd64/v8
        ports: ['8545:8545']
        entrypoint:
            [
                'anvil',
                '--fork-url',
                'https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}',
                '--fork-block-number',
                '6093396',
                '--host',
                '0.0.0.0',
            ]
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'wget -q -O - http://0.0.0.0:8545 --post-data ''{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}'' --header=''Content-Type: application/json'' || exit 1',
                ]
            interval: 2s
            timeout: 5s
            retries: 5

    alto:
        image: chnejohnson/alto:0.0.11
        ports: ['4337:4337']
        command: --config alto.config.json
        volumes:
            - ./alto.config.json:/app/alto.config.json
        healthcheck:
            test: ['CMD-SHELL', 'wget -q -O - http://0.0.0.0:4337/health || exit 1']
            interval: 2s
            timeout: 5s
            retries: 5
        depends_on:
            anvil:
                condition: service_healthy

    deploy-contracts:
        image: ghcr.io/foundry-rs/foundry:nightly-503792a1dbadd901a4c02f6fcd1de1caff1573ff
        platform: linux/amd64/v8
        volumes:
            - ./contracts:/app/contracts
            - ./.env:/app/contracts/.env
        working_dir: /app
        command:
            [
                'cd contracts && forge install --no-git && forge build && forge script script/deploy-contracts.s.sol --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://anvil:8545 --broadcast',
            ]
        depends_on:
            anvil:
                condition: service_healthy
            alto:
                condition: service_healthy
