/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TIFallback,
  TIFallbackInterface,
} from "../../../manual/IERC7579Modules.sol/TIFallback";

const _abi = [
  {
    type: "function",
    name: "isInitialized",
    inputs: [
      {
        name: "smartAccount",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isModuleType",
    inputs: [
      {
        name: "moduleTypeId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onInstall",
    inputs: [
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "onUninstall",
    inputs: [
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "error",
    name: "AlreadyInitialized",
    inputs: [
      {
        name: "smartAccount",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotInitialized",
    inputs: [
      {
        name: "smartAccount",
        type: "address",
        internalType: "address",
      },
    ],
  },
] as const;

export class TIFallback__factory {
  static readonly abi = _abi;
  static createInterface(): TIFallbackInterface {
    return new Interface(_abi) as TIFallbackInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TIFallback {
    return new Contract(address, _abi, runner) as unknown as TIFallback;
  }
}
