/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { TIERC1271, TIERC1271Interface } from "../../manual/TIERC1271";

const _abi = [
  {
    type: "function",
    name: "isValidSignature",
    inputs: [
      {
        name: "_dataHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "_signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class TIERC1271__factory {
  static readonly abi = _abi;
  static createInterface(): TIERC1271Interface {
    return new Interface(_abi) as TIERC1271Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): TIERC1271 {
    return new Contract(address, _abi, runner) as unknown as TIERC1271;
  }
}
