[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via-ir = true # for src/validators/webauthn/WebAuthn.sol:153:55: Stack too deep

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
solady = "0.1.3"
kernel = { version = "3.1", git = "https://github.com/zerodevapp/kernel.git", tag = "v3.1" }
aa = { version = "0.7", git = "https://github.com/eth-infinitism/account-abstraction.git", tag = "v0.7.0" }
oz = { version = "5.1", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.1.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
