[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true # for src/validators/webauthn/WebAuthn.sol:153:55:

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
