[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via-ir = true # for src/validators/webauthn/WebAuthn.sol:153:55: Stack too deep

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
eth-infinitism-account-abstraction = "0.7"
solady = "0.1.3"
kernel = { version = "3.1", git = "https://github.com/zerodevapp/kernel.git", tag = "v3.1" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
