/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TCounterInterface extends Interface {
  getFunction(
    nameOrSignature: "increment" | "number" | "setNumber"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NumberIncremented" | "NumberSet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "increment", values?: undefined): string;
  encodeFunctionData(functionFragment: "number", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setNumber",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "increment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "number", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setNumber", data: BytesLike): Result;
}

export namespace NumberIncrementedEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NumberSetEvent {
  export type InputTuple = [caller: AddressLike, newNumber: BigNumberish];
  export type OutputTuple = [caller: string, newNumber: bigint];
  export interface OutputObject {
    caller: string;
    newNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TCounter extends BaseContract {
  connect(runner?: ContractRunner | null): TCounter;
  waitForDeployment(): Promise<this>;

  interface: TCounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  increment: TypedContractMethod<[], [void], "nonpayable">;

  number: TypedContractMethod<[], [bigint], "view">;

  setNumber: TypedContractMethod<
    [newNumber: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "increment"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "number"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setNumber"
  ): TypedContractMethod<[newNumber: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "NumberIncremented"
  ): TypedContractEvent<
    NumberIncrementedEvent.InputTuple,
    NumberIncrementedEvent.OutputTuple,
    NumberIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "NumberSet"
  ): TypedContractEvent<
    NumberSetEvent.InputTuple,
    NumberSetEvent.OutputTuple,
    NumberSetEvent.OutputObject
  >;

  filters: {
    "NumberIncremented(address)": TypedContractEvent<
      NumberIncrementedEvent.InputTuple,
      NumberIncrementedEvent.OutputTuple,
      NumberIncrementedEvent.OutputObject
    >;
    NumberIncremented: TypedContractEvent<
      NumberIncrementedEvent.InputTuple,
      NumberIncrementedEvent.OutputTuple,
      NumberIncrementedEvent.OutputObject
    >;

    "NumberSet(address,uint256)": TypedContractEvent<
      NumberSetEvent.InputTuple,
      NumberSetEvent.OutputTuple,
      NumberSetEvent.OutputObject
    >;
    NumberSet: TypedContractEvent<
      NumberSetEvent.InputTuple,
      NumberSetEvent.OutputTuple,
      NumberSetEvent.OutputObject
    >;
  };
}
