/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type PackedUserOperationStruct = {
  sender: AddressLike;
  nonce: BigNumberish;
  initCode: BytesLike;
  callData: BytesLike;
  accountGasLimits: BytesLike;
  preVerificationGas: BigNumberish;
  gasFees: BytesLike;
  paymasterAndData: BytesLike;
  signature: BytesLike;
};

export type PackedUserOperationStructOutput = [
  sender: string,
  nonce: bigint,
  initCode: string,
  callData: string,
  accountGasLimits: string,
  preVerificationGas: bigint,
  gasFees: string,
  paymasterAndData: string,
  signature: string
] & {
  sender: string;
  nonce: bigint;
  initCode: string;
  callData: string;
  accountGasLimits: string;
  preVerificationGas: bigint;
  gasFees: string;
  paymasterAndData: string;
  signature: string;
};

export interface TECDSAValidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ecdsaValidatorStorage"
      | "isInitialized"
      | "isModuleType"
      | "isValidSignatureWithSender"
      | "onInstall"
      | "onUninstall"
      | "postCheck"
      | "preCheck"
      | "validateUserOp"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnerRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "ecdsaValidatorStorage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isModuleType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignatureWithSender",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onInstall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onUninstall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "postCheck",
    values: [BytesLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "preCheck",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateUserOp",
    values: [PackedUserOperationStruct, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ecdsaValidatorStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isModuleType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignatureWithSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onInstall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onUninstall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postCheck", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "preCheck", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateUserOp",
    data: BytesLike
  ): Result;
}

export namespace OwnerRegisteredEvent {
  export type InputTuple = [kernel: AddressLike, owner: AddressLike];
  export type OutputTuple = [kernel: string, owner: string];
  export interface OutputObject {
    kernel: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TECDSAValidator extends BaseContract {
  connect(runner?: ContractRunner | null): TECDSAValidator;
  waitForDeployment(): Promise<this>;

  interface: TECDSAValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ecdsaValidatorStorage: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  isInitialized: TypedContractMethod<
    [smartAccount: AddressLike],
    [boolean],
    "view"
  >;

  isModuleType: TypedContractMethod<[typeID: BigNumberish], [boolean], "view">;

  isValidSignatureWithSender: TypedContractMethod<
    [arg0: AddressLike, hash: BytesLike, sig: BytesLike],
    [string],
    "view"
  >;

  onInstall: TypedContractMethod<[_data: BytesLike], [void], "payable">;

  onUninstall: TypedContractMethod<[arg0: BytesLike], [void], "payable">;

  postCheck: TypedContractMethod<
    [hookData: BytesLike, success: boolean, res: BytesLike],
    [void],
    "payable"
  >;

  preCheck: TypedContractMethod<
    [msgSender: AddressLike, value: BigNumberish, arg2: BytesLike],
    [string],
    "payable"
  >;

  validateUserOp: TypedContractMethod<
    [userOp: PackedUserOperationStruct, userOpHash: BytesLike],
    [bigint],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ecdsaValidatorStorage"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[smartAccount: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isModuleType"
  ): TypedContractMethod<[typeID: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidSignatureWithSender"
  ): TypedContractMethod<
    [arg0: AddressLike, hash: BytesLike, sig: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "onInstall"
  ): TypedContractMethod<[_data: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "onUninstall"
  ): TypedContractMethod<[arg0: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "postCheck"
  ): TypedContractMethod<
    [hookData: BytesLike, success: boolean, res: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "preCheck"
  ): TypedContractMethod<
    [msgSender: AddressLike, value: BigNumberish, arg2: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "validateUserOp"
  ): TypedContractMethod<
    [userOp: PackedUserOperationStruct, userOpHash: BytesLike],
    [bigint],
    "payable"
  >;

  getEvent(
    key: "OwnerRegistered"
  ): TypedContractEvent<
    OwnerRegisteredEvent.InputTuple,
    OwnerRegisteredEvent.OutputTuple,
    OwnerRegisteredEvent.OutputObject
  >;

  filters: {
    "OwnerRegistered(address,address)": TypedContractEvent<
      OwnerRegisteredEvent.InputTuple,
      OwnerRegisteredEvent.OutputTuple,
      OwnerRegisteredEvent.OutputObject
    >;
    OwnerRegistered: TypedContractEvent<
      OwnerRegisteredEvent.InputTuple,
      OwnerRegisteredEvent.OutputTuple,
      OwnerRegisteredEvent.OutputObject
    >;
  };
}
