/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type PackedUserOperationStruct = {
  sender: AddressLike;
  nonce: BigNumberish;
  initCode: BytesLike;
  callData: BytesLike;
  accountGasLimits: BytesLike;
  preVerificationGas: BigNumberish;
  gasFees: BytesLike;
  paymasterAndData: BytesLike;
  signature: BytesLike;
};

export type PackedUserOperationStructOutput = [
  sender: string,
  nonce: bigint,
  initCode: string,
  callData: string,
  accountGasLimits: string,
  preVerificationGas: bigint,
  gasFees: string,
  paymasterAndData: string,
  signature: string
] & {
  sender: string;
  nonce: bigint;
  initCode: string;
  callData: string;
  accountGasLimits: string;
  preVerificationGas: bigint;
  gasFees: string;
  paymasterAndData: string;
  signature: string;
};

export interface TWebAuthnValidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isInitialized"
      | "isModuleType"
      | "isValidSignatureWithSender"
      | "onInstall"
      | "onUninstall"
      | "validateUserOp"
      | "webAuthnValidatorStorage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "WebAuthnPublicKeyRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isModuleType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignatureWithSender",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onInstall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onUninstall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateUserOp",
    values: [PackedUserOperationStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "webAuthnValidatorStorage",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isModuleType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignatureWithSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onInstall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onUninstall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateUserOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "webAuthnValidatorStorage",
    data: BytesLike
  ): Result;
}

export namespace WebAuthnPublicKeyRegisteredEvent {
  export type InputTuple = [
    kernel: AddressLike,
    authenticatorIdHash: BytesLike,
    pubKeyX: BigNumberish,
    pubKeyY: BigNumberish
  ];
  export type OutputTuple = [
    kernel: string,
    authenticatorIdHash: string,
    pubKeyX: bigint,
    pubKeyY: bigint
  ];
  export interface OutputObject {
    kernel: string;
    authenticatorIdHash: string;
    pubKeyX: bigint;
    pubKeyY: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TWebAuthnValidator extends BaseContract {
  connect(runner?: ContractRunner | null): TWebAuthnValidator;
  waitForDeployment(): Promise<this>;

  interface: TWebAuthnValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isInitialized: TypedContractMethod<
    [smartAccount: AddressLike],
    [boolean],
    "view"
  >;

  isModuleType: TypedContractMethod<[typeID: BigNumberish], [boolean], "view">;

  isValidSignatureWithSender: TypedContractMethod<
    [sender: AddressLike, hash: BytesLike, data: BytesLike],
    [string],
    "view"
  >;

  onInstall: TypedContractMethod<[_data: BytesLike], [void], "payable">;

  onUninstall: TypedContractMethod<[arg0: BytesLike], [void], "payable">;

  validateUserOp: TypedContractMethod<
    [_userOp: PackedUserOperationStruct, _userOpHash: BytesLike],
    [bigint],
    "payable"
  >;

  webAuthnValidatorStorage: TypedContractMethod<
    [kernel: AddressLike],
    [[bigint, bigint] & { pubKeyX: bigint; pubKeyY: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[smartAccount: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isModuleType"
  ): TypedContractMethod<[typeID: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidSignatureWithSender"
  ): TypedContractMethod<
    [sender: AddressLike, hash: BytesLike, data: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "onInstall"
  ): TypedContractMethod<[_data: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "onUninstall"
  ): TypedContractMethod<[arg0: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "validateUserOp"
  ): TypedContractMethod<
    [_userOp: PackedUserOperationStruct, _userOpHash: BytesLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "webAuthnValidatorStorage"
  ): TypedContractMethod<
    [kernel: AddressLike],
    [[bigint, bigint] & { pubKeyX: bigint; pubKeyY: bigint }],
    "view"
  >;

  getEvent(
    key: "WebAuthnPublicKeyRegistered"
  ): TypedContractEvent<
    WebAuthnPublicKeyRegisteredEvent.InputTuple,
    WebAuthnPublicKeyRegisteredEvent.OutputTuple,
    WebAuthnPublicKeyRegisteredEvent.OutputObject
  >;

  filters: {
    "WebAuthnPublicKeyRegistered(address,bytes32,uint256,uint256)": TypedContractEvent<
      WebAuthnPublicKeyRegisteredEvent.InputTuple,
      WebAuthnPublicKeyRegisteredEvent.OutputTuple,
      WebAuthnPublicKeyRegisteredEvent.OutputObject
    >;
    WebAuthnPublicKeyRegistered: TypedContractEvent<
      WebAuthnPublicKeyRegisteredEvent.InputTuple,
      WebAuthnPublicKeyRegisteredEvent.OutputTuple,
      WebAuthnPublicKeyRegisteredEvent.OutputObject
    >;
  };
}
