/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7579AccountEvents,
  IERC7579AccountEventsInterface,
} from "../../../manual/IERC7579Account.sol/IERC7579AccountEvents";

const _abi = [
  {
    type: "event",
    name: "ModuleInstalled",
    inputs: [
      {
        name: "moduleTypeId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "module",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ModuleUninstalled",
    inputs: [
      {
        name: "moduleTypeId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "module",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
] as const;

export class IERC7579AccountEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7579AccountEventsInterface {
    return new Interface(_abi) as IERC7579AccountEventsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7579AccountEvents {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC7579AccountEvents;
  }
}
