name: CI

on:
    push:
        branches:
            - main
            - dev

    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
            SALT: ${{ secrets.SALT }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: stable

            - name: Install dependencies
              run: bun install

            - name: Create .env file
              run: |
                  echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
                  echo "SALT=${{ secrets.SALT }}" >> .env
                  echo "PIMLICO_API_KEY=${{ secrets.PIMLICO_API_KEY }}" >> .env
                  echo "PIMLICO_SPONSORSHIP_POLICY_ID=${{ secrets.PIMLICO_SPONSORSHIP_POLICY_ID }}" >> .env

            - name: Start Docker services
              run: |
                  docker compose up -d

            - name: Install Forge dependencies
              run: |
                  cd contracts/
                  forge soldeer install

            - name: Deploy contracts
              run: bun deploy-contracts:local

            - name: Build project
              run: bun run build

            - name: Run tests
              run: bun run test

            - name: Stop Docker services
              if: always()
              run: docker compose down
